# Generated by Django 4.0.3 on 2022-04-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='usersN',
        ),
    ]
